//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace easySync.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("easySync.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup folder [{0}] does not exist. Do you want to continue and save this pair?.
        /// </summary>
        internal static string BackupFolderDoesNotExistFormat {
            get {
                return ResourceManager.GetString("BackupFolderDoesNotExistFormat", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Cancel_16x16 {
            get {
                object obj = ResourceManager.GetObject("Cancel_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete pair with source path [{0}] and destination path [{1}]?.
        /// </summary>
        internal static string DeletePairFormat {
            get {
                return ResourceManager.GetString("DeletePairFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete pair?.
        /// </summary>
        internal static string DeletePairTitle {
            get {
                return ResourceManager.GetString("DeletePairTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination folder [{0}] does not exist. Do you want to continue and save this pair?.
        /// </summary>
        internal static string DestinationFolderDoesNotExistFormat {
            get {
                return ResourceManager.GetString("DestinationFolderDoesNotExistFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occoured in easySync: {0} - {1}.
        /// </summary>
        internal static string ErrorFormat {
            get {
                return ResourceManager.GetString("ErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to easySync error.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder does not exist.
        /// </summary>
        internal static string FolderDoesNotExistTitle {
            get {
                return ResourceManager.GetString("FolderDoesNotExistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string MenuItemClose {
            get {
                return ResourceManager.GetString("MenuItemClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause all activities.
        /// </summary>
        internal static string MenuItemPause {
            get {
                return ResourceManager.GetString("MenuItemPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show settings.
        /// </summary>
        internal static string MenuItemShow {
            get {
                return ResourceManager.GetString("MenuItemShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to easySync v{0}.
        /// </summary>
        internal static string NotifyIconTextFormat {
            get {
                return ResourceManager.GetString("NotifyIconTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re running version {0} which is most recent version of easySync..
        /// </summary>
        internal static string NoUpdatesFormat {
            get {
                return ResourceManager.GetString("NoUpdatesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to easySync is up to date.
        /// </summary>
        internal static string NoUpdatesTitle {
            get {
                return ResourceManager.GetString("NoUpdatesTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Pause_16x16 {
            get {
                object obj = ResourceManager.GetObject("Pause_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Settings_16x16 {
            get {
                object obj = ResourceManager.GetObject("Settings_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source folder [{0}] does not exist. Do you want to continue and save this pair?.
        /// </summary>
        internal static string SourceFolderDoesNotExistFormat {
            get {
                return ResourceManager.GetString("SourceFolderDoesNotExistFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added..
        /// </summary>
        internal static string StatusAdded {
            get {
                return ResourceManager.GetString("StatusAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing....
        /// </summary>
        internal static string StatusClosing {
            get {
                return ResourceManager.GetString("StatusClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted..
        /// </summary>
        internal static string StatusDeleted {
            get {
                return ResourceManager.GetString("StatusDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused..
        /// </summary>
        internal static string StatusPaused {
            get {
                return ResourceManager.GetString("StatusPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready..
        /// </summary>
        internal static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started..
        /// </summary>
        internal static string StatusStarted {
            get {
                return ResourceManager.GetString("StatusStarted", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Stop_16x16 {
            get {
                object obj = ResourceManager.GetObject("Stop_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon sync_notify {
            get {
                object obj = ResourceManager.GetObject("sync_notify", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep daily archives for last month.
        /// </summary>
        internal static string SyncBackupKeepMonth {
            get {
                return ResourceManager.GetString("SyncBackupKeepMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep monthly archives for last year.
        /// </summary>
        internal static string SyncBackupKeepMonthly {
            get {
                return ResourceManager.GetString("SyncBackupKeepMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep daily archives for last week.
        /// </summary>
        internal static string SyncBackupKeepWeek {
            get {
                return ResourceManager.GetString("SyncBackupKeepWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep weekly archives for last month.
        /// </summary>
        internal static string SyncBackupKeepWeekly {
            get {
                return ResourceManager.GetString("SyncBackupKeepWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep weekly archives for last year.
        /// </summary>
        internal static string SyncBackupKeepYear {
            get {
                return ResourceManager.GetString("SyncBackupKeepYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No backups.
        /// </summary>
        internal static string SyncBackupNoBackups {
            get {
                return ResourceManager.GetString("SyncBackupNoBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync changes every hour.
        /// </summary>
        internal static string SyncStrategyHours1 {
            get {
                return ResourceManager.GetString("SyncStrategyHours1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync changes every 3 hours.
        /// </summary>
        internal static string SyncStrategyHours3 {
            get {
                return ResourceManager.GetString("SyncStrategyHours3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync changes every 6 hours.
        /// </summary>
        internal static string SyncStrategyHours6 {
            get {
                return ResourceManager.GetString("SyncStrategyHours6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync all changes immediately.
        /// </summary>
        internal static string SyncStrategyImmediately {
            get {
                return ResourceManager.GetString("SyncStrategyImmediately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync changes on start only.
        /// </summary>
        internal static string SyncStrategyOnStart {
            get {
                return ResourceManager.GetString("SyncStrategyOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated version of easySync is available. You&apos;re running version {0} while {1} is available. Would you like to download and install it?.
        /// </summary>
        internal static string UpdateAvailableFormat {
            get {
                return ResourceManager.GetString("UpdateAvailableFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates for easySync are available.
        /// </summary>
        internal static string UpdateAvailableTitle {
            get {
                return ResourceManager.GetString("UpdateAvailableTitle", resourceCulture);
            }
        }
    }
}
